const authModal = {
  LABEL_FORGOT_PASSWORD: 'पासवर्ड विसरलात?',
  LABEL_FORGOT_USERNAME: 'वापरकर्तानाव विसरलात?',
  LABEL_USERNAME_OR_EMAIL: 'वापरकर्तानाव किंवा ईमेल',
  LABEL_CONTINUING_TERMS: 'सुरू ठेवून, तुम्ही आमच्याशी सहमत होता',
  LABEL_TERMS_OF_USE: 'वापरण्याच्या अटी',
  LABEL_CREATE_AN_ACCOUNT: 'खाते तयार करा',
  LABEL_OR_SIGN_IN_WITH: 'किंवा सह साइन इन करा',
  LABEL_INCORRECT_EMAIL: 'चुकीचा इ - मेल पत्ता',
  LABEL_OR_SIGN_UP_WITH: 'किंवा सह साइन अप करा',
  LABEL_PASSWORD: 'पासवर्ड',
  LABEL_ONE_MORE_STEP_AHEAD: 'आणखी एक पाऊल पुढे!',
  LABEL_WE_SENT: 'आम्ही पाठवले आहे',
  LABEL_6_CHAR_CODE: '6 वर्ण कोड',
  LABEL_TO_THIS_EMAIL: 'या ईमेलवर',
  LABEL_TO_VERIFY_YOUR_ACCOUNT: 'तुमचे खाते सत्यापित करण्यासाठी',
  LABEL_TO_VERIFY_ITS_YOU: 'ते तुम्हीच आहात याची पडताळणी करण्यासाठी',
  LABEL_VERIFY: 'सत्यापित करा',
  LABEL_RESEND_CODE: 'कोड पुन्हा पाठवा',
  LABEL_TY_JOINING_US: 'आमच्यात सामील झाल्याबद्दल धन्यवाद!',
  LABEL_SIGNUP_SUCCESS_MSG: 'तुमचे खाते यशस्वीरित्या सत्यापित केले गेले आहे. तुम्ही आता तुमची क्रेडेन्शियल वापरून साइन इन करू शकता किंवा तुमचे प्रारंभिक प्रोफाइल सेट करण्यासाठी पुढे जा वर क्लिक करा.',
  LABEL_CHECKING_IF_USER_EXISTS: 'वापरकर्ता अस्तित्वात आहे का ते तपासत आहे',
  LABEL_SIGNIN_INSTEAD: 'त्याऐवजी साइन इन करा',
  LABEL_CHANGE_PASSWORD: 'पासवर्ड बदला',
  LABEL_PASSWORD_RESET_SUCCESS: 'पासवर्ड रीसेट यशस्वी!',
  LABEL_SUCCESS_CHANGE_PASSWORD: 'तुमचा नवीन पासवर्ड यशस्वीरित्या सेट केला गेला आहे. तुम्ही आता तुमचा नवीन पासवर्ड वापरून साइन इन करू शकता किंवा थेट साइन इन करण्यासाठी पुढे जा क्लिक करा.',
  LABEL_VERIFICATION_FORM_INSTRUCTION: 'हे खाते तयार करण्यासाठी तुम्ही वापरलेल्या ईमेलवर. कृपया तुमचे खाते सत्यापित करण्यासाठी फॉर्ममध्ये कोड टाका',
  FORM_VALIDATION_EMAIL_REQUIRED: 'ईमेल आवश्यक आहे',
  FORM_VALIDATION_USERNAME_MATCH: 'क्षमस्व, फक्त अक्षरे (a-z), संख्या (0-9), विशेष वर्ण (.-_) कोणत्याही जागेची परवानगी नाही.',
  FORM_VALIDATION_USERNAME_MAX: 'वापरकर्ता नावाची लांबी 32 पेक्षा कमी किंवा समान असणे आवश्यक आहे',
  FORM_VALIDATION_USERNAME_REQUIRED: 'वापरकर्तानाव आवश्यक आहे',
  FORM_VALIDATION_PASSWORD_REQUIRED: 'पासवर्ड आवश्यक आहे',
  FORM_VALIDATION_PASSWORD_MIN: '12 वर्णांपेक्षा मोठे असणे आवश्यक आहे',
  FORM_VALIDATION_CODE_REQUIRED: 'कोड आवश्यक आहे',
  FORM_VALIDATION_CODE_MIN: '6 वर्ण असणे आवश्यक आहे',
  FORM_VALIDATION_CODE_MAX: '6 वर्ण असणे आवश्यक आहे',
  FORM_VALIDATION_NEW_PASSWORD_REQUIRED: 'नवीन पासवर्ड आवश्यक आहे'
};
export default authModal;