const authModal = {
  LABEL_FORGOT_PASSWORD: 'mot de passe oublié?',
  LABEL_FORGOT_USERNAME: 'identifiant oublié?',
  LABEL_USERNAME_OR_EMAIL: "Nom d'utilisateur ou email",
  LABEL_CONTINUING_TERMS: 'En continuant, vous acceptez nos',
  LABEL_TERMS_OF_USE: "Conditions d'utilisation",
  LABEL_CREATE_AN_ACCOUNT: 'Créer un compte',
  LABEL_OR_SIGN_IN_WITH: 'ou connectez-vous avec',
  LABEL_INCORRECT_EMAIL: 'Adresse e-mail incorrecte',
  LABEL_OR_SIGN_UP_WITH: 'ou inscrivez-vous avec',
  LABEL_PASSWORD: 'Mot de passe',
  LABEL_ONE_MORE_STEP_AHEAD: 'Un pas de plus en avant !',
  LABEL_WE_SENT: 'Nous avons envoyé un',
  LABEL_6_CHAR_CODE: 'Code à 6 caractères',
  LABEL_TO_THIS_EMAIL: 'à cet e-mail',
  LABEL_TO_VERIFY_YOUR_ACCOUNT: 'pour vérifier votre compte',
  LABEL_TO_VERIFY_ITS_YOU: "pour vérifier que c'est bien toi",
  LABEL_VERIFY: 'Vérifier',
  LABEL_RESEND_CODE: 'Renvoyer le code',
  LABEL_TY_JOINING_US: 'Merci de nous avoir rejoint!',
  LABEL_SIGNUP_SUCCESS_MSG: "Votre compte a été vérifié avec succès. Vous pouvez maintenant vous connecter à l'aide de vos informations d'identification ou cliquer sur Continuer pour configurer votre profil initial.",
  LABEL_CHECKING_IF_USER_EXISTS: "Vérifier si l'utilisateur existe",
  LABEL_SIGNIN_INSTEAD: 'Connectez-vous plutôt',
  LABEL_CHANGE_PASSWORD: 'Changer le mot de passe',
  LABEL_PASSWORD_RESET_SUCCESS: 'Réinitialisation du mot de passe réussie !',
  LABEL_SUCCESS_CHANGE_PASSWORD: 'Votre nouveau mot de passe a été défini avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe ou cliquer sur Continuer pour vous connecter directement.',
  LABEL_VERIFICATION_FORM_INSTRUCTION: 'on the email you used creating this account. Please put the code in the form to verify your account',
  FORM_VALIDATION_EMAIL_REQUIRED: 'Email is required',
  FORM_VALIDATION_USERNAME_MATCH: 'Sorry, only letters (a-z), numbers (0-9), special characters (.-_) no space are allowed.',
  FORM_VALIDATION_USERNAME_MAX: "Le nom d'utilisateur doit avoir une longueur inférieure ou égale à 32",
  FORM_VALIDATION_USERNAME_REQUIRED: "Nom d'utilisateur est nécessaire",
  FORM_VALIDATION_PASSWORD_REQUIRED: 'Mot de passe requis',
  FORM_VALIDATION_PASSWORD_MIN: 'Doit contenir plus de 12 caractères',
  FORM_VALIDATION_CODE_REQUIRED: 'Le code est requis',
  FORM_VALIDATION_CODE_MIN: 'Doit contenir 6 caractères',
  FORM_VALIDATION_CODE_MAX: 'Doit contenir 6 caractères',
  FORM_VALIDATION_NEW_PASSWORD_REQUIRED: 'Un nouveau mot de passe est requis'
};
export default authModal;