const common = {
  LABEL_FILTERS: 'फिल्टर',
  LABEL_CHAPTERS: 'अध्याय',
  LABEL_CHAPTER: 'धडा',
  LABEL_SERIES: 'मालिका',
  LABEL_CREATOR: 'निर्माता',
  LABEL_SEARCH: 'शोधा',
  LABEL_ACCOUNT: 'माझे खाते',
  LABEL_SIGN_IN: 'साइन इन करा',
  AUTH_MODAL_HEADING: 'उत्कट कॉमिक वाचक, लेखक आणि कलाकारांच्या समुदायाचा भाग व्हा.',
  LABEL_CREATE: 'तयार करा',
  LABEL_INSTEAD: ' instead',
  LABEL_EMAIL: 'ईमेल',
  LABEL_USERNAME: 'वापरकर्तानाव',
  LABEL_PASSWORD: 'पासवर्ड',
  LABEL_NEXT: 'पुढे',
  LABEL_PROCEED: 'पुढे जा',
  LABEL_ONGOING: 'चालू आहे',
  LABEL_COLLABORATORS: 'सहयोगी',
  LABEL_NO_COLLABORATORS: 'कोणतेही सहयोगी नाहीत',
  LABEL_ADD: 'अॅड',
  LABEL_REMOVE: 'काढा',
  LABEL_CAN_EDIT: 'संपादित करू शकतो',
  LABEL_CAN_VIEW: 'पाहू शकतो',
  LABEL_SHARE_WITH_SOMEONE_PLACEHOLDER: 'कोणाशी तरी शेअर करा...',
  LABEL_LOADING: 'लोड करत आहे...',
  LABEL_PAGE: 'पान',
  LABEL_PAGES: 'पृष्ठे',
  LABEL_AUTH_GUARD_CHECKING_AUTH: 'प्रमाणीकरण तपासत आहे',
  LABEL_AUTH_GUARD_REDIRECT_MSG: 'अप्रमाणित - आम्ही तुम्हाला घरी पुनर्निर्देशित करू',
  LABEL_USER_CARD_TITLE: 'अनामिक',
  LABEL_USER_CARD_SUB_HEADER: 'साइन इन करा किंवा खाते तयार करून आमच्यात सामील व्हा',
  LABEL_READS: 'वाचतो',
  LABEL_LIKES: 'आवडी',
  LABEL_LIKE: 'आवडले',
  LABEL_PRIVACY_POLICY: 'गोपनीयता धोरण',
  LABEL_TERMS_OF_SERVICE: 'सेवा अटी',
  LABEL_COOKIE_POLICY: 'कुकी धोरण',
  LABEL_SIGN_UP: 'साइन अप करा',
  LABEL_SETTINGS: 'सेटिंग्ज',
  LABEL_LANGUAGES: 'भाषा',
  LABEL_FAQ: 'मदत आणि वारंवार विचारले जाणारे प्रश्न',
  LABEL_APPS: 'अॅप्स',
  FOOTER_ABOUT_US: 'उत्कट कॉमिक वाचक, लेखक आणि कलाकारांच्या समुदायाचा भाग व्हा',
  LABEL_SEARCH_SERIES: 'मालिका शोधत आहे...',
  LABEL_MY_PROFILE: 'माझे प्रोफाइल',
  LABEL_MY_ACCOUNT_SETTINGS: 'माझे खाते सेटिंग्ज',
  LABEL_SIGNED_IN_AS: 'म्हणून साइन इन केले',
  LABEL_NO_SERIES_FOUND: 'कोणतीही मालिका आढळली नाही',
  LABEL_PRIVATE_VIEW: 'खाजगी दृश्य',
  LABEL_CREATE_SERIES: 'मालिका तयार करा',
  LABEL_SERIES_LIST: 'मालिका यादी',
  //COMMENTS
  LABEL_COMMENT_HIDE: 'टिप्पण्या लपवा',
  LABEL_COMMENT_SHOW: 'टिप्पण्या दर्शवा',
  LABEL_COMMENT: 'टिप्पणी',
  LABEL_COMMENTS: 'टिप्पण्या',
  LABEL_VIEW: 'पहा',
  LABEL_REPLIES: 'प्रत्युत्तरे',
  LABEL_REPLY: 'उत्तर द्या',
  LABEL_HIDE_REPLY: 'उत्तर लपवा',
  LABEL_HIDE_REPLIES: 'प्रत्युत्तरे लपवा',
  LABEL_CANCEL: 'रद्द करा',
  LABEL_ADD_A_REPLY: 'धाग्याला उत्तर द्या',
  LABEL_ADD_A_COMMENT: 'एक टिप्पणी जोडा...',
  LABEL_PLEASE_SIGNIN_COMMENT: 'कृपया टिप्पणी जोडण्यासाठी साइन इन करा.',
  LABEL_MORE_COMMENTS: 'अधिक टिप्पण्या',
  LABEL_SHOW_MORE_REPLIES: 'अधिक उत्तरे दाखवा',
  LABEL_ADD_EDIT_COMMENT: 'टिप्पणी संपादित करा.',
  LABEL_BEST: 'सर्वोत्तम',
  LABEL_NEWEST: 'सर्वात नवीन',
  LABEL_OLDEST: 'सर्वात जुनी',
  LABEL_EDIT: 'सुधारणे',
  LABEL_ERROR_COMMENT_NOT_EXIST: 'टिप्पणी अस्तित्वात नाही.',
  LABEL_ERROR_VOTE_OWN_COMMENT: 'तुम्ही तुमची स्वतःची टिप्पणी करू शकत नाही.',
  LABEL_ERROR_ALREADY_UPVOTE: 'तुम्ही या टिप्पणीला आधीच समर्थन दिले आहे.',
  LABEL_ERROR_ALREADY_DOWNVOTE: 'तुम्ही आधीच ही टिप्पणी नाकारली आहे.',
  LABEL_CONFIRM_DELETE_COMMENT: 'तुम्हाला ही टिप्पणी हटवायची आहे का?',
  //BACKEND ERROR MESSAGE
  ERR_MSG_USERNAME_EXIST: 'वापरकर्तानाव आधीपासूनच वापरात आहे',
  ERR_MSG_WRONG_USERNAME_OR_PASSWORD: 'वापरकर्त्याचे नाव अथवा पासवर्ड चुकीचा',
  ERR_MSG_REQUEST_LIMIT: 'विनंती मर्यादा पोहोच! कृपया पुन्हा प्रयत्न करा',
  ERR_MSG_DEFAULT: 'अरेरे काहीतरी चूक झाली! कृपया पुन्हा प्रयत्न करा',
  ERR_MSG_EMAIL_EXIST: 'समान ईमेल पत्ता असलेला वापरकर्ता अस्तित्वात आहे',
  SOCIAL_EMAIL_ERROR_MESSAGE: 'तुम्ही वापरण्याचा प्रयत्न केलेला ईमेल असलेले खाते आधीपासून अस्तित्वात असल्याचे दिसते.',
  TOOLTIP_WEBSITE_LANGUAGE: 'संपूर्ण वेबसाइटची भाषा बदलते',
  TOOLTIP_COMICS_LANGUAGES: 'तुम्हाला वाचण्यात स्वारस्य असलेल्या कॉमिक्ससाठी भाषा फिल्टर',
  LABEL_MY_DASHBOARD: 'माझा डॅशबोर्ड'
};
export default common;