const authModal = {
  LABEL_FORGOT_PASSWORD: '¿Se te olvidó tu contraseña?',
  LABEL_FORGOT_USERNAME: '¿Olvidó su nombre de usuario?',
  LABEL_USERNAME_OR_EMAIL: 'Nombre de usuario o correo electrónico',
  LABEL_CONTINUING_TERMS: 'Al continuar, aceptas nuestros',
  LABEL_TERMS_OF_USE: 'Términos de Uso',
  LABEL_CREATE_AN_ACCOUNT: 'Crea una cuenta',
  LABEL_OR_SIGN_IN_WITH: 'o inicia sesión con',
  LABEL_INCORRECT_EMAIL: 'Dirección de E-Mail incorrecta',
  LABEL_OR_SIGN_UP_WITH: 'o regístrate con',
  LABEL_PASSWORD: 'Clave',
  LABEL_ONE_MORE_STEP_AHEAD: '¡Un paso más adelante!',
  LABEL_WE_SENT: 'hemos enviado un',
  LABEL_6_CHAR_CODE: 'código de 6 caracteres',
  LABEL_TO_THIS_EMAIL: 'a este correo',
  LABEL_TO_VERIFY_YOUR_ACCOUNT: 'para verificar tu cuenta',
  LABEL_TO_VERIFY_ITS_YOU: 'para verificar que eres tu',
  LABEL_VERIFY: 'Verificar',
  LABEL_RESEND_CODE: 'Reenviar codigo',
  LABEL_TY_JOINING_US: '¡Gracias por estar con nosotros!',
  LABEL_SIGNUP_SUCCESS_MSG: 'Your account has been successfully verified. You can now sign in using your credentials, or click proceed to setup your initial profile.',
  LABEL_CHECKING_IF_USER_EXISTS: 'Checking if user exists',
  LABEL_SIGNIN_INSTEAD: 'Sign-in instead',
  LABEL_CHANGE_PASSWORD: 'Change password',
  LABEL_PASSWORD_RESET_SUCCESS: 'Password reset success!',
  LABEL_SUCCESS_CHANGE_PASSWORD: 'Your new password has been successfully set. You can now sign in using your new password, or click proceed to be signed in directly.',
  LABEL_VERIFICATION_FORM_INSTRUCTION: 'on the email you used creating this account. Please put the code in the form to verify your account',
  FORM_VALIDATION_EMAIL_REQUIRED: 'Email is required',
  FORM_VALIDATION_USERNAME_MATCH: 'Sorry, only letters (a-z), numbers (0-9), special characters (.-_) no space are allowed.',
  FORM_VALIDATION_USERNAME_MAX: 'Username must have length less than or equal to 32',
  FORM_VALIDATION_USERNAME_REQUIRED: 'Username is required',
  FORM_VALIDATION_PASSWORD_REQUIRED: 'Password is required',
  FORM_VALIDATION_PASSWORD_MIN: 'Must be longer than 12 characters',
  FORM_VALIDATION_CODE_REQUIRED: 'Code is required',
  FORM_VALIDATION_CODE_MIN: 'Must be 6 characters',
  FORM_VALIDATION_CODE_MAX: 'Must be 6 characters',
  FORM_VALIDATION_NEW_PASSWORD_REQUIRED: 'New password is required'
};
export default authModal;