const common = {
  LABEL_FILTERS: 'フィルター',
  LABEL_CHAPTERS: '章',
  LABEL_CHAPTER: '章',
  LABEL_SERIES: 'シリーズ',
  LABEL_CREATOR: 'クリエイター',
  LABEL_SEARCH: '検索',
  LABEL_SIGN_IN: 'ログイン',
  AUTH_MODAL_HEADING: 'お好みの漫画をお探しします。',
  LABEL_CREATE: '作成する',
  LABEL_INSTEAD: '代わりに',
  LABEL_EMAIL: 'メールアドレス',
  LABEL_USERNAME: 'ユーザー名',
  LABEL_PASSWORD: 'パスワード',
  LABEL_NEXT: '次',
  LABEL_PROCEED: '続行する',
  LABEL_ONGOING: '進行中',
  LABEL_COLLABORATORS: '共同編集者',
  LABEL_NO_COLLABORATORS: '共同編集者なし',
  LABEL_ADD: '追加',
  LABEL_REMOVE: '削除する',
  LABEL_CAN_EDIT: '編集することができます',
  LABEL_CAN_VIEW: '見ることができます',
  LABEL_SHARE_WITH_SOMEONE_PLACEHOLDER: '誰かと共有する...',
  LABEL_LOADING: '読み込み中...',
  LABEL_PAGE: 'ページ',
  LABEL_PAGES: 'ページ',
  LABEL_AUTH_GUARD_CHECKING_AUTH: '認証中',
  LABEL_AUTH_GUARD_REDIRECT_MSG: '認証されませんでした。ホーム画面に戻ります。',
  LABEL_USER_CARD_TITLE: 'ランダムシード',
  LABEL_USER_CARD_SUB_HEADER: 'ログインまたは新規登録',
  LABEL_READS: '読者数',
  LABEL_LIKES: '読者数',
  LABEL_PRIVACY_POLICY: 'プライバシーポリシー',
  LABEL_TERMS_OF_SERVICE: '利用規約',
  LABEL_COOKIE_POLICY: `クッキーポリシー`,
  LABEL_SIGN_UP: '新規登録',
  LABEL_SETTINGS: '設定',
  LABEL_LANGUAGES: '言語',
  LABEL_FAQ: 'ヘルプとFAQ',
  LABEL_APPS: 'Apps',
  FOOTER_ABOUT_US:
    '私たちはコミック愛好家のためのコミュニティを創造しています。',
  LABEL_SEARCH_SERIES: `シリーズを検索しています...`,
  LABEL_NO_SERIES_FOUND: 'シリーズが見つかりません',
  LABEL_PRIVATE_VIEW: 'プライベートビュー',
  LABEL_CREATE_SERIES: 'シリーズを作成する',
  LABEL_SERIES_LIST: 'シリーズリスト',
  //COMMENTS
  LABEL_COMMENT: 'コメント',
  LABEL_COMMENTS: 'コメント',
  LABEL_VIEW: '見る',
  LABEL_REPLIES: '返信',
  LABEL_REPLY: '応答',
  LABEL_HIDE_REPLY: '返信を隠す',
  LABEL_HIDE_REPLIES: '返信を非表示',
  LABEL_CANCEL: 'キャンセル',
  LABEL_ADD_A_REPLY: 'スレッドに返信',
  LABEL_ADD_A_COMMENT: 'コメントを追加...',
  LABEL_PLEASE_SIGNIN_COMMENT:
    'コメントを追加するには、サインインしてください。',
  LABEL_MORE_COMMENTS: 'その他のコメント',
  LABEL_SHOW_MORE_REPLIES: '返信をもっと見る',
  LABEL_ADD_EDIT_COMMENT: 'コメントを編集します。',
  LABEL_BEST: 'ベスト',
  LABEL_NEWEST: '最新',
  LABEL_OLDEST: '最古',
  LABEL_EDIT: '編集',
  LABEL_ERROR_COMMENT_NOT_EXIST: 'コメントはありません。',
  LABEL_ERROR_VOTE_OWN_COMMENT: '自分のコメントに投票することはできません。',
  LABEL_ERROR_ALREADY_UPVOTE: 'あなたはすでにこのコメントに賛成しています。',
  LABEL_ERROR_ALREADY_DOWNVOTE:
    'あなたはすでにこのコメントに反対票を投じています。',
  LABEL_CONFIRM_DELETE_COMMENT: 'このコメントを削除しますか？',
  //BACKEND ERROR MESSAGE
  ERR_MSG_USERNAME_EXIST: 'ユーザー名は既に使用されています。',
  ERR_MSG_WRONG_USERNAME_OR_PASSWORD:
    'ユーザー名またはパスワードが正しくありません。',
  ERR_MSG_REQUEST_LIMIT:
    '要求回数の制限を超えました。しばらくしてからもう一度お試し下さい。',
  ERR_MSG_DEFAULT:
    '予期せぬエラーが発生しました。しばらくしてからもう一度お試しください。',
  ERR_MSG_EMAIL_EXIST: '既に登録されているメールアドレスです。',
  SOCIAL_EMAIL_ERROR_MESSAGE:
    '使用しようとしたメールアドレスのアカウントは既に存在しているようです。',
  TOOLTIP_WEBSITE_LANGUAGE: 'Webサイト全体の言語を変更します',
  TOOLTIP_COMICS_LANGUAGES: '読書に興味がある漫画のための言語フィルター',
};

export default common;
