const authModal = {
  LABEL_FORGOT_PASSWORD: 'Nakalimutan ang password?',
  LABEL_FORGOT_USERNAME: 'Nakalimutan ang username?',
  LABEL_USERNAME_OR_EMAIL: 'Username o Email',
  LABEL_CONTINUING_TERMS: 'Sa pagpapatuloy, sumasang-ayon ka sa aming',
  LABEL_TERMS_OF_USE: 'Mga Tuntunin ng Paggamit',
  LABEL_CREATE_AN_ACCOUNT: 'Gumawa ng account',
  LABEL_OR_SIGN_IN_WITH: 'o mag-sign in gamit ang',
  LABEL_INCORRECT_EMAIL: 'Maling email address',
  LABEL_OR_SIGN_UP_WITH: 'o mag-sign up sa',
  LABEL_PASSWORD: 'Password',
  LABEL_ONE_MORE_STEP_AHEAD: 'Isang hakbang pa sa unahan!',
  LABEL_WE_SENT: 'Nagpadala kami ng isang',
  LABEL_6_CHAR_CODE: '6 na character code',
  LABEL_TO_THIS_EMAIL: 'sa email na ito',
  LABEL_TO_VERIFY_YOUR_ACCOUNT: 'upang i-verify ang iyong account',
  LABEL_TO_VERIFY_ITS_YOU: 'para ma-verify na ikaw iyon',
  LABEL_VERIFY: 'I-verify',
  LABEL_RESEND_CODE: 'Muling ipadala ang code',
  LABEL_TY_JOINING_US: 'Salamat sa pagsali sa amin!',
  LABEL_SIGNUP_SUCCESS_MSG: 'Ang iyong account ay matagumpay na na-verify. Maaari ka na ngayong mag-sign in gamit ang iyong mga kredensyal, o i-click ang magpatuloy upang i-setup ang iyong unang profile.',
  LABEL_CHECKING_IF_USER_EXISTS: 'Sinusuri kung may gumagamit',
  LABEL_SIGNIN_INSTEAD: 'Mag-sign-in na lang',
  LABEL_CHANGE_PASSWORD: 'Palitan ANG password',
  LABEL_PASSWORD_RESET_SUCCESS: 'Tagumpay ang pag-reset ng password!',
  LABEL_SUCCESS_CHANGE_PASSWORD: 'Ang iyong bagong password ay matagumpay na naitakda. Maaari ka na ngayong mag-sign in gamit ang iyong bagong password, o i-click ang magpatuloy upang direktang ma-sign in.',
  LABEL_VERIFICATION_FORM_INSTRUCTION: 'sa email na ginamit mo sa paggawa ng account na ito. Mangyaring ilagay ang code sa form upang i-verify ang iyong account',
  FORM_VALIDATION_EMAIL_REQUIRED: 'Kinakailangan ang email',
  FORM_VALIDATION_USERNAME_MATCH: 'Paumanhin, tanging mga titik (a-z), numero (0-9), mga espesyal na character (.-_) walang puwang ang pinapayagan.',
  FORM_VALIDATION_USERNAME_MAX: 'Ang username ay dapat na may haba na mas mababa sa o katumbas ng 32',
  FORM_VALIDATION_USERNAME_REQUIRED: 'Kinakailangan ang username',
  FORM_VALIDATION_PASSWORD_REQUIRED: 'Kinakailangan ang password',
  FORM_VALIDATION_PASSWORD_MIN: 'Dapat ay mas mahaba sa 12 character',
  FORM_VALIDATION_CODE_REQUIRED: 'Kinakailangan ang code',
  FORM_VALIDATION_CODE_MIN: 'Dapat ay 6 na character',
  FORM_VALIDATION_CODE_MAX: 'Dapat ay 6 na character',
  FORM_VALIDATION_NEW_PASSWORD_REQUIRED: 'Kinakailangan ang bagong password'
};
export default authModal;