const genres = {
  GENRE_ALL: 'Todos',
  GENRE_ACTION: 'Acción',
  GENRE_ADVENTURE: 'Aventura',
  GENRE_COMEDY: 'Comedia',
  GENRE_CYBERPUNK: 'ciberpunk',
  GENRE_DEMONS: 'demonios',
  GENRE_DRAMA: 'Drama',
  GENRE_FANTASY: 'Fantasy',
  GENRE_GAME: 'Game',
  GENRE_HISTORICAL: 'Historical',
  GENRE_HORROR: 'Horror',
  GENRE_KIDS: 'Kids',
  GENRE_LGBTQ: 'LGBTQ+',
  GENRE_MAGIC: 'Magic',
  GENRE_MATURE: 'Mature',
  GENRE_MECHA: 'Mecha',
  GENRE_MILITARY: 'Military',
  GENRE_MUSIC: 'Music',
  GENRE_MYSTERY: 'Mystery',
  GENRE_PARODY: 'Parody',
  GENRE_POLICE: 'Police',
  GENRE_POST_APOCALYPTIC: 'Post-Apocalyptic',
  GENRE_PSYCHOLOGICAL: 'Psychological',
  GENRE_REVERSE_HAREM: 'Reverse Harem',
  GENRE_ROMANCE: 'Romance',
  GENRE_SCHOOL: 'Escuela',
  GENRE_SCI_FI: 'Ciencia ficción',
  GENRE_SLICE_OF_LIFE: 'Rebanada de vida',
  GENRE_SPACE: 'Espacio',
  GENRE_SPORTS: 'Deportes',
  GENRE_SUPER_POWER: 'superpoder',
  GENRE_SUPERNATURAL: 'Sobrenatural',
  GENRE_TRAGEDY: 'Tragedia',
  GENRE_VAMPIRE: 'Vampiro',
};

export default genres;
