const common = {
  LABEL_FILTERS: 'filtros',
  LABEL_CHAPTERS: 'Capítulos',
  LABEL_CHAPTER: 'Capítulo',
  LABEL_SERIES: 'Serie',
  LABEL_CREATOR: 'Creador',
  LABEL_SEARCH: 'Búsqueda',
  LABEL_ACCOUNT: 'Mi cuenta',
  LABEL_SIGN_IN: 'Iniciar sesión',
  AUTH_MODAL_HEADING: 'Be part of a community of passionate comic readers, writers, and artists.',
  LABEL_CREATE: 'Create',
  LABEL_INSTEAD: ' instead',
  LABEL_EMAIL: 'Correo electrónico',
  LABEL_USERNAME: 'Nombre de usuario',
  LABEL_PASSWORD: 'Clave',
  LABEL_NEXT: 'próximo',
  LABEL_PROCEED: 'Proceder',
  LABEL_ONGOING: 'En curso',
  LABEL_COLLABORATORS: 'Colaboradores',
  LABEL_NO_COLLABORATORS: 'Sin colaboradores',
  LABEL_ADD: 'Agregar',
  LABEL_REMOVE: 'Remover',
  LABEL_CAN_EDIT: 'Poder editar',
  LABEL_CAN_VIEW: 'Puedo ver',
  LABEL_SHARE_WITH_SOMEONE_PLACEHOLDER: 'Comparte con alguien...',
  LABEL_LOADING: 'Cargando...',
  LABEL_PAGE: 'Página',
  LABEL_PAGES: 'Paginas',
  LABEL_AUTH_GUARD_CHECKING_AUTH: 'Comprobación de la autenticación',
  LABEL_AUTH_GUARD_REDIRECT_MSG: 'Sin autenticar: lo redirigiremos a su hogar',
  LABEL_USER_CARD_TITLE: 'Anónimo',
  LABEL_USER_CARD_SUB_HEADER: 'Inicia sesión o únete a nosotros creando una cuenta',
  LABEL_READS: 'Lee',
  LABEL_LIKES: 'Gustos',
  LABEL_LIKE: 'Me gusta',
  LABEL_PRIVACY_POLICY: 'Política de privacidad',
  LABEL_TERMS_OF_SERVICE: 'Términos de servicio',
  LABEL_COOKIE_POLICY: 'Política de cookies',
  LABEL_SIGN_UP: 'Inscribirse',
  LABEL_SETTINGS: 'Ajustes',
  LABEL_LANGUAGES: 'Idiomas',
  LABEL_FAQ: 'Ayuda y preguntas frecuentes',
  LABEL_APPS: 'aplicaciones',
  FOOTER_ABOUT_US: 'Be part of a community of passionate comic readers, writers, and artists',
  LABEL_SEARCH_SERIES: 'Searching for series...',
  LABEL_MY_PROFILE: 'My Profile',
  LABEL_MY_ACCOUNT_SETTINGS: 'My Account Settings',
  LABEL_SIGNED_IN_AS: 'Signed in as',
  LABEL_NO_SERIES_FOUND: 'No Series Found',
  LABEL_PRIVATE_VIEW: 'Private View',
  LABEL_CREATE_SERIES: 'Create Series',
  LABEL_SERIES_LIST: 'Series List',
  //COMMENTS
  LABEL_COMMENT_HIDE: 'Hide Comments',
  LABEL_COMMENT_SHOW: 'Show Comments',
  LABEL_COMMENT: 'Comment',
  LABEL_COMMENTS: 'Comments',
  LABEL_VIEW: 'View',
  LABEL_REPLIES: 'Replies',
  LABEL_REPLY: 'Reply',
  LABEL_HIDE_REPLY: 'Hide reply',
  LABEL_HIDE_REPLIES: 'Hide replies',
  LABEL_CANCEL: 'Cancel',
  LABEL_ADD_A_REPLY: 'Reply to thread',
  LABEL_ADD_A_COMMENT: 'Add a comment...',
  LABEL_PLEASE_SIGNIN_COMMENT: 'Please signin to add a comment.',
  LABEL_MORE_COMMENTS: 'More comments',
  LABEL_SHOW_MORE_REPLIES: 'Show more replies',
  LABEL_ADD_EDIT_COMMENT: 'Edit comment.',
  LABEL_BEST: 'Best',
  LABEL_NEWEST: 'Newest',
  LABEL_OLDEST: 'Oldest',
  LABEL_EDIT: 'Edit',
  LABEL_ERROR_COMMENT_NOT_EXIST: 'Comment is not exist.',
  LABEL_ERROR_VOTE_OWN_COMMENT: 'You cannot vote your own comment.',
  LABEL_ERROR_ALREADY_UPVOTE: 'You already upvote this comment.',
  LABEL_ERROR_ALREADY_DOWNVOTE: 'You already downvote this comment.',
  LABEL_CONFIRM_DELETE_COMMENT: 'Do you want to delete this comment?',
  //BACKEND ERROR MESSAGE
  ERR_MSG_USERNAME_EXIST: 'Username is already in use',
  ERR_MSG_WRONG_USERNAME_OR_PASSWORD: 'Incorrect username or password',
  ERR_MSG_REQUEST_LIMIT: 'Request limit reach! Please try again later',
  ERR_MSG_DEFAULT: 'Ooops something went wrong! Please try again later',
  ERR_MSG_EMAIL_EXIST: 'A user with the same email address exists',
  SOCIAL_EMAIL_ERROR_MESSAGE: 'It looks like an account with the email you tried to use already exist.',
  TOOLTIP_WEBSITE_LANGUAGE: 'Changes the language of the whole website',
  TOOLTIP_COMICS_LANGUAGES: 'Filtro de idioma para los cómics que te interesa leer',
  LABEL_MY_DASHBOARD: 'Mi tablero'
};
export default common;