const common = {
  LABEL_FILTERS: 'Filter',
  LABEL_CHAPTERS: 'bab',
  LABEL_CHAPTER: 'Bab',
  LABEL_SERIES: 'Seri',
  LABEL_CREATOR: 'Pencipta',
  LABEL_SEARCH: 'Mencari',
  LABEL_ACCOUNT: 'Akun saya',
  LABEL_SIGN_IN: 'Masuk',
  AUTH_MODAL_HEADING: 'Jadilah bagian dari komunitas pembaca komik, penulis, dan seniman yang bersemangat.',
  LABEL_CREATE: 'Membuat',
  LABEL_INSTEAD: ' instead',
  LABEL_EMAIL: 'Surel',
  LABEL_USERNAME: 'Nama belakang',
  LABEL_PASSWORD: 'Kata sandi',
  LABEL_NEXT: 'Lanjut',
  LABEL_PROCEED: 'Melanjutkan',
  LABEL_ONGOING: 'Sedang berlangsung',
  LABEL_COLLABORATORS: 'Kolaborator',
  LABEL_NO_COLLABORATORS: 'Tidak Ada Kolaborator',
  LABEL_ADD: 'Menambahkan',
  LABEL_REMOVE: 'Menghapus',
  LABEL_CAN_EDIT: 'Dapat mengedit',
  LABEL_CAN_VIEW: 'Dapat melihat',
  LABEL_SHARE_WITH_SOMEONE_PLACEHOLDER: 'Berbagi dengan seseorang...',
  LABEL_LOADING: 'Memuat...',
  LABEL_PAGE: 'Halaman',
  LABEL_PAGES: 'halaman',
  LABEL_AUTH_GUARD_CHECKING_AUTH: 'Memeriksa otentikasi',
  LABEL_AUTH_GUARD_REDIRECT_MSG: 'Tidak diautentikasi - kami akan mengarahkan Anda ke rumah',
  LABEL_USER_CARD_TITLE: 'Anonim',
  LABEL_USER_CARD_SUB_HEADER: 'Masuk atau bergabunglah dengan kami dengan membuat akun',
  LABEL_READS: 'Bacaan',
  LABEL_LIKES: 'Suka',
  LABEL_LIKE: 'Suka',
  LABEL_PRIVACY_POLICY: 'Kebijakan pribadi',
  LABEL_TERMS_OF_SERVICE: 'Persyaratan Layanan',
  LABEL_COOKIE_POLICY: 'Kebijakan Cookie',
  LABEL_SIGN_UP: 'Daftar',
  LABEL_SETTINGS: 'Pengaturan',
  LABEL_LANGUAGES: 'Bahasa',
  LABEL_FAQ: 'Bantuan & FAQ',
  LABEL_APPS: 'Aplikasi',
  FOOTER_ABOUT_US: 'Jadilah bagian dari komunitas pembaca komik, penulis, dan seniman yang bersemangat',
  LABEL_SEARCH_SERIES: 'Mencari seri...',
  LABEL_MY_PROFILE: 'Profil saya',
  LABEL_MY_ACCOUNT_SETTINGS: 'Pengaturan Akun Saya',
  LABEL_SIGNED_IN_AS: 'Masuk sebagai',
  LABEL_NO_SERIES_FOUND: 'Tidak Ada Seri yang Ditemukan',
  LABEL_PRIVATE_VIEW: 'Pemandangan Pribadi',
  LABEL_CREATE_SERIES: 'Buat Seri',
  LABEL_SERIES_LIST: 'Daftar Seri',
  //COMMENTS
  LABEL_COMMENT_HIDE: 'Sembunyikan Komentar',
  LABEL_COMMENT_SHOW: 'Tampilkan Komentar',
  LABEL_COMMENT: 'Komentar',
  LABEL_COMMENTS: 'Komentar',
  LABEL_VIEW: 'Melihat',
  LABEL_REPLIES: 'Balasan',
  LABEL_REPLY: 'Membalas',
  LABEL_HIDE_REPLY: 'Sembunyikan balasan',
  LABEL_HIDE_REPLIES: 'Sembunyikan balasan',
  LABEL_CANCEL: 'Membatalkan',
  LABEL_ADD_A_REPLY: 'Balas ke utas',
  LABEL_ADD_A_COMMENT: 'Tambahkan komentar...',
  LABEL_PLEASE_SIGNIN_COMMENT: 'Silakan masuk untuk menambahkan komentar.',
  LABEL_MORE_COMMENTS: 'Lebih banyak komentar',
  LABEL_SHOW_MORE_REPLIES: 'Tampilkan lebih banyak balasan',
  LABEL_ADD_EDIT_COMMENT: 'Mengedit komentar.',
  LABEL_BEST: 'Terbaik',
  LABEL_NEWEST: 'Terbaru',
  LABEL_OLDEST: 'tertua',
  LABEL_EDIT: 'Sunting',
  LABEL_ERROR_COMMENT_NOT_EXIST: 'Komentar tidak ada.',
  LABEL_ERROR_VOTE_OWN_COMMENT: 'Anda tidak dapat memilih komentar Anda sendiri.',
  LABEL_ERROR_ALREADY_UPVOTE: 'Anda sudah memberi suara positif pada komentar ini.',
  LABEL_ERROR_ALREADY_DOWNVOTE: 'Anda sudah tidak menyukai komentar ini.',
  LABEL_CONFIRM_DELETE_COMMENT: 'Apakah Anda ingin menghapus komentar ini?',
  //BACKEND ERROR MESSAGE
  ERR_MSG_USERNAME_EXIST: 'nama pengguna telah digunakan',
  ERR_MSG_WRONG_USERNAME_OR_PASSWORD: 'Username atau kata sandi salah',
  ERR_MSG_REQUEST_LIMIT: 'Permintaan mencapai batas! Silakan coba lagi nanti',
  ERR_MSG_DEFAULT: 'Ups ada yang tidak beres! Silakan coba lagi nanti',
  ERR_MSG_EMAIL_EXIST: 'Ada pengguna dengan alamat email yang sama',
  SOCIAL_EMAIL_ERROR_MESSAGE: 'Sepertinya akun dengan email yang Anda coba gunakan sudah ada.',
  TOOLTIP_WEBSITE_LANGUAGE: 'Mengubah bahasa seluruh situs web',
  TOOLTIP_COMICS_LANGUAGES: 'Filter bahasa untuk komik yang Anda minati',
  LABEL_MY_DASHBOARD: 'Dasbor saya'
};
export default common;