const genres = {
  GENRE_ALL: '모두',
  GENRE_ACTION: '동작',
  GENRE_ADVENTURE: '모험',
  GENRE_COMEDY: '코메디',
  GENRE_CYBERPUNK: '사이버펑크',
  GENRE_DEMONS: '악마',
  GENRE_DRAMA: '드라마',
  GENRE_FANTASY: '공상',
  GENRE_GAME: '게임',
  GENRE_HISTORICAL: '역사적인',
  GENRE_HORROR: '공포',
  GENRE_KIDS: '어린이',
  GENRE_LGBTQ: 'LGBTQ+',
  GENRE_MAGIC: '마법',
  GENRE_MATURE: '성숙한',
  GENRE_MECHA: '메카',
  GENRE_MILITARY: '군대',
  GENRE_MUSIC: '음악',
  GENRE_MYSTERY: '신비',
  GENRE_PARODY: '풍자적 개작 시문',
  GENRE_POLICE: '경찰',
  GENRE_POST_APOCALYPTIC: '종말 이후',
  GENRE_PSYCHOLOGICAL: '심리적',
  GENRE_REVERSE_HAREM: '리버스 하렘',
  GENRE_ROMANCE: '로맨스',
  GENRE_SCHOOL: '학교',
  GENRE_SCI_FI: '공상 과학',
  GENRE_SLICE_OF_LIFE: '생명의 조각',
  GENRE_SPACE: '우주',
  GENRE_SPORTS: '스포츠',
  GENRE_SUPER_POWER: '슈퍼파워',
  GENRE_SUPERNATURAL: '신의 조화',
  GENRE_TRAGEDY: '비극',
  GENRE_VAMPIRE: '흡혈귀'
};
export default genres;