const common = {
  LABEL_FILTERS: 'Filters',
  LABEL_CHAPTERS: 'Chapters',
  LABEL_CHAPTER: 'Chapter',
  LABEL_SERIES: 'Series',
  LABEL_CREATOR: 'Creator',
  LABEL_SEARCH: 'Search',
  LABEL_ACCOUNT: 'My Account',
  LABEL_SIGN_IN: 'Sign in',
  AUTH_MODAL_HEADING:
    'Be part of a community of passionate comic readers, writers, and artists.',
  LABEL_CREATE: 'Create',
  LABEL_INSTEAD: ' instead',
  LABEL_EMAIL: 'ईमेल',
  LABEL_USERNAME: 'उपयोगकर्ता नाम',
  LABEL_PASSWORD: 'पासवर्ड',
  LABEL_NEXT: 'अगला',
  LABEL_PROCEED: 'आगे बढ़ना',
  LABEL_ONGOING: 'चल रहे',
  LABEL_COLLABORATORS: 'सहयोगियों',
  LABEL_NO_COLLABORATORS: 'कोई सहयोगी नहीं',
  LABEL_ADD: 'जोड़ें',
  LABEL_REMOVE: 'हटाना',
  LABEL_CAN_EDIT: 'संपादित कर सकते हैं',
  LABEL_CAN_VIEW: 'देख सकते हैं',
  LABEL_SHARE_WITH_SOMEONE_PLACEHOLDER: 'किसी के साथ साझा करें...',
  LABEL_LOADING: 'लोड हो रहा है...',
  LABEL_PAGE: 'पृष्ठ',
  LABEL_PAGES: 'पृष्ठों',
  LABEL_AUTH_GUARD_CHECKING_AUTH: 'प्रमाणीकरण की जाँच',
  LABEL_AUTH_GUARD_REDIRECT_MSG:
    'अनधिकृत - हम आपको घर पर पुनर्निर्देशित करेंगे',
  LABEL_USER_CARD_TITLE: 'अनाम',
  LABEL_USER_CARD_SUB_HEADER: 'साइन इन करें या खाता बनाकर हमसे जुड़ें',
  LABEL_READS: 'पुस्तकें',
  LABEL_LIKES: 'को यह पसंद है',
  LABEL_LIKE: 'पसंद करना',
  LABEL_PRIVACY_POLICY: 'गोपनीयता नीति',
  LABEL_TERMS_OF_SERVICE: 'सेवा की शर्तें',
  LABEL_COOKIE_POLICY: 'कूकी नीति',
  LABEL_SIGN_UP: 'साइन अप करें',
  LABEL_SETTINGS: 'समायोजन',
  LABEL_LANGUAGES: 'बोली',
  LABEL_FAQ: 'सहायता और अक्सर पूछे जाने वाले प्रश्न',
  LABEL_APPS: 'ऐप्स',
  FOOTER_ABOUT_US:
    'Be part of a community of passionate comic readers, writers, and artists',
  LABEL_SEARCH_SERIES: 'Searching for series...',
  LABEL_MY_PROFILE: 'My Profile',
  LABEL_MY_ACCOUNT_SETTINGS: 'My Account Settings',
  LABEL_SIGNED_IN_AS: 'Signed in as',
  LABEL_NO_SERIES_FOUND: 'No Series Found',
  LABEL_PRIVATE_VIEW: 'Private View',
  LABEL_CREATE_SERIES: 'Create Series',
  LABEL_SERIES_LIST: 'Series List',
  //COMMENTS
  LABEL_COMMENT_HIDE: 'टिप्पणियाँ छुपाएं',
  LABEL_COMMENT_SHOW: 'टिप्पणियाँ दिखाएँ',
  LABEL_COMMENT: 'टिप्पणी',
  LABEL_COMMENTS: 'टिप्पणियाँ',
  LABEL_VIEW: 'राय',
  LABEL_REPLIES: 'जवाब',
  LABEL_REPLY: 'जवाब',
  LABEL_HIDE_REPLY: 'उत्तर छुपाएं',
  LABEL_HIDE_REPLIES: 'उत्तर छुपाएं',
  LABEL_CANCEL: 'रद्द करना',
  LABEL_ADD_A_REPLY: 'सूत्र का उत्तर दें',
  LABEL_ADD_A_COMMENT: 'एक टिप्पणी जोड़ने...',
  LABEL_PLEASE_SIGNIN_COMMENT: 'कृपया टिप्पणी शमिल करने के लिए साइन इन करें।',
  LABEL_MORE_COMMENTS: 'अधिक टिप्पणियाँ',
  LABEL_SHOW_MORE_REPLIES: 'अधिक उत्तर दिखाएं',
  LABEL_ADD_EDIT_COMMENT: 'टिप्पणी संपादित करें।',
  LABEL_BEST: 'श्रेष्ठ',
  LABEL_NEWEST: 'नवीनतम',
  LABEL_OLDEST: 'सबसे पुराने',
  LABEL_EDIT: 'संपादन करना',
  LABEL_ERROR_COMMENT_NOT_EXIST: 'टिप्पणी मौजूद नहीं है।',
  LABEL_ERROR_VOTE_OWN_COMMENT: 'आप अपनी टिप्पणी को वोट नहीं दे सकते।',
  LABEL_ERROR_ALREADY_UPVOTE: 'आप इस टिप्पणी को पहले ही अपवोट कर चुके हैं।',
  LABEL_ERROR_ALREADY_DOWNVOTE: 'आप इस टिप्पणी को पहले ही डाउनवोट कर चुके हैं।',
  LABEL_CONFIRM_DELETE_COMMENT: 'क्या आपकी इस टिप्पणी को हटाने की चाहत है?',
  //BACKEND ERROR MESSAGE
  ERR_MSG_USERNAME_EXIST: 'उपयोगकर्ता का नाम पहले से ही उपयोग किया जा रहा है',
  ERR_MSG_WRONG_USERNAME_OR_PASSWORD: 'गलत उपयोगकर्ता नाम या पासवर्ड',
  ERR_MSG_REQUEST_LIMIT: 'अनुरोध सीमा पहुंच! बाद में पुन: प्रयास करें',
  ERR_MSG_DEFAULT: 'उफ़ कुछ गलत हो गया! बाद में पुन: प्रयास करें',
  ERR_MSG_EMAIL_EXIST: 'समान ईमेल पते वाला उपयोगकर्ता मौजूद है',
  SOCIAL_EMAIL_ERROR_MESSAGE:
    'It looks like an account with the email you tried to use already exist.',
  TOOLTIP_WEBSITE_LANGUAGE: 'Changes the language of the whole website',
  TOOLTIP_COMICS_LANGUAGES:
    'उन कॉमिक्स के लिए भाषा फ़िल्टर जिन्हें आप पढ़ने में रुचि रखते हैं',
  LABEL_MY_DASHBOARD: 'मेरे यंत्र रखने की जगह',
};

export default common;
