const common = {
  LABEL_FILTERS: 'Filters',
  LABEL_CHAPTERS: 'Chapters',
  LABEL_CHAPTER: 'Chapter',
  LABEL_SERIES: 'Series',
  LABEL_CREATOR: 'Creator',
  LABEL_SEARCH: 'Search',
  LABEL_ACCOUNT: 'My Account',
  LABEL_SIGN_IN: 'Sign in',
  AUTH_MODAL_HEADING: 'Be part of a community of passionate comic readers, writers, and artists.',
  LABEL_CREATE: 'Create',
  LABEL_INSTEAD: ' instead',
  LABEL_EMAIL: 'Email',
  LABEL_USERNAME: 'Username',
  LABEL_PASSWORD: 'Password',
  LABEL_NEXT: 'Next',
  LABEL_PROCEED: 'Proceed',
  LABEL_ONGOING: 'Ongoing',
  LABEL_COLLABORATORS: 'Collaborators',
  LABEL_NO_COLLABORATORS: 'No Collaborators',
  LABEL_ADD: 'Add',
  LABEL_REMOVE: 'Remove',
  LABEL_CAN_EDIT: 'Can edit',
  LABEL_CAN_VIEW: 'Can view',
  LABEL_SHARE_WITH_SOMEONE_PLACEHOLDER: 'Share with someone...',
  LABEL_LOADING: 'Loading...',
  LABEL_PAGE: 'Page',
  LABEL_PAGES: 'Pages',
  LABEL_AUTH_GUARD_CHECKING_AUTH: 'Checking authentication',
  LABEL_AUTH_GUARD_REDIRECT_MSG: 'Unauthenticated - we will redirect you to home',
  LABEL_USER_CARD_TITLE: 'Anonymous',
  LABEL_USER_CARD_SUB_HEADER: 'Sign in or join us by creating an account',
  LABEL_READS: 'Reads',
  LABEL_LIKES: 'Likes',
  LABEL_LIKE: 'Like',
  LABEL_PRIVACY_POLICY: 'Privacy Policy',
  LABEL_TERMS_OF_SERVICE: 'Terms of Service',
  LABEL_COOKIE_POLICY: 'Cookie Policy',
  LABEL_SIGN_UP: 'Sign up',
  LABEL_SETTINGS: 'Settings',
  LABEL_LANGUAGES: 'Languages',
  LABEL_FAQ: 'Help & FAQ',
  LABEL_APPS: 'Apps',
  FOOTER_ABOUT_US: 'Be part of a community of passionate comic readers, writers, and artists',
  LABEL_SEARCH_SERIES: 'Searching for series...',
  LABEL_MY_PROFILE: 'My Profile',
  LABEL_MY_ACCOUNT_SETTINGS: 'My Account Settings',
  LABEL_SIGNED_IN_AS: 'Signed in as',
  LABEL_NO_SERIES_FOUND: 'No Series Found',
  LABEL_PRIVATE_VIEW: 'Private View',
  LABEL_CREATE_SERIES: 'Create Series',
  LABEL_SERIES_LIST: 'Series List',
  //COMMENTS
  LABEL_COMMENT_HIDE: 'Hide Comments',
  LABEL_COMMENT_SHOW: 'Show Comments',
  LABEL_COMMENT: 'Comment',
  LABEL_COMMENTS: 'Comments',
  LABEL_VIEW: 'View',
  LABEL_REPLIES: 'Replies',
  LABEL_REPLY: 'Reply',
  LABEL_HIDE_REPLY: 'Hide reply',
  LABEL_HIDE_REPLIES: 'Hide replies',
  LABEL_CANCEL: 'Cancel',
  LABEL_ADD_A_REPLY: 'Reply to thread',
  LABEL_ADD_A_COMMENT: 'Add a comment...',
  LABEL_PLEASE_SIGNIN_COMMENT: 'Please signin to add a comment.',
  LABEL_MORE_COMMENTS: 'More comments',
  LABEL_SHOW_MORE_REPLIES: 'Show more replies',
  LABEL_ADD_EDIT_COMMENT: 'Edit comment.',
  LABEL_BEST: 'Best',
  LABEL_NEWEST: 'Newest',
  LABEL_OLDEST: 'Oldest',
  LABEL_EDIT: 'Edit',
  LABEL_ERROR_COMMENT_NOT_EXIST: 'Comment is not exist.',
  LABEL_ERROR_VOTE_OWN_COMMENT: 'You cannot vote your own comment.',
  LABEL_ERROR_ALREADY_UPVOTE: 'You already upvote this comment.',
  LABEL_ERROR_ALREADY_DOWNVOTE: 'You already downvote this comment.',
  LABEL_CONFIRM_DELETE_COMMENT: 'Do you want to delete this comment?',
  //BACKEND ERROR MESSAGE
  ERR_MSG_USERNAME_EXIST: 'Username is already in use',
  ERR_MSG_WRONG_USERNAME_OR_PASSWORD: 'Incorrect username or password',
  ERR_MSG_REQUEST_LIMIT: 'Request limit reach! Please try again later',
  ERR_MSG_DEFAULT: 'Ooops something went wrong! Please try again later',
  ERR_MSG_EMAIL_EXIST: 'A user with the same email address exists',
  SOCIAL_EMAIL_ERROR_MESSAGE: 'It looks like an account with the email you tried to use already exist.',
  TOOLTIP_WEBSITE_LANGUAGE: 'Changes the language of the whole website',
  TOOLTIP_COMICS_LANGUAGES: 'Language filter for the comics you are interested in reading',
  LABEL_MY_DASHBOARD: 'My Dashboard'
};
export default common;