const common = {
  LABEL_FILTERS: 'フィルター',
  LABEL_CHAPTERS: '章',
  LABEL_CHAPTER: '章',
  LABEL_SERIES: 'シリーズ',
  LABEL_CREATOR: 'クリエイター',
  LABEL_SEARCH: '探す',
  LABEL_ACCOUNT: 'マイアカウント',
  LABEL_SIGN_IN: 'ログイン',
  AUTH_MODAL_HEADING:
    '情熱的なコミック リーダー、ライター、アーティストのコミュニティの一員になりましょう。',
  LABEL_CREATE: '作成',
  LABEL_INSTEAD: ' instead',
  LABEL_EMAIL: 'Eメール',
  LABEL_USERNAME: 'ユーザー名',
  LABEL_PASSWORD: 'パスワード',
  LABEL_NEXT: '次',
  LABEL_PROCEED: '続行',
  LABEL_ONGOING: '進行中',
  LABEL_COLLABORATORS: '協力者',
  LABEL_NO_COLLABORATORS: 'コラボレーターなし',
  LABEL_ADD: '追加',
  LABEL_REMOVE: '削除する',
  LABEL_CAN_EDIT: '編集することができます',
  LABEL_CAN_VIEW: '閲覧可能',
  LABEL_SHARE_WITH_SOMEONE_PLACEHOLDER: '誰かと共有...',
  LABEL_LOADING: '読み込んでいます...',
  LABEL_PAGE: 'ページ',
  LABEL_PAGES: 'ページ',
  LABEL_AUTH_GUARD_CHECKING_AUTH: '認証の確認',
  LABEL_AUTH_GUARD_REDIRECT_MSG:
    '認証されていません - ホームにリダイレクトされます',
  LABEL_USER_CARD_TITLE: '匿名',
  LABEL_USER_CARD_SUB_HEADER:
    'サインインするか、アカウントを作成して参加してください',
  LABEL_READS: '読み取り',
  LABEL_LIKES: 'いいね',
  LABEL_LIKE: 'お気に入り',
  LABEL_PRIVACY_POLICY: 'プライバシーポリシー',
  LABEL_TERMS_OF_SERVICE: '利用規約',
  LABEL_COOKIE_POLICY: 'クッキーポリシー',
  LABEL_SIGN_UP: 'サインアップ',
  LABEL_SETTINGS: '設定',
  LABEL_LANGUAGES: '言語',
  LABEL_FAQ: 'ヘルプとよくある質問',
  LABEL_APPS: 'アプリ',
  FOOTER_ABOUT_US:
    '情熱的なコミック リーダー、ライター、アーティストのコミュニティの一員になりましょう',
  LABEL_SEARCH_SERIES: 'シリーズを検索しています...',
  LABEL_MY_PROFILE: '私のプロフィール',
  LABEL_MY_ACCOUNT_SETTINGS: 'マイアカウント設定',
  LABEL_SIGNED_IN_AS: '次のユーザーとしてサインインしました',
  LABEL_NO_SERIES_FOUND: 'シリーズが見つかりません',
  LABEL_PRIVATE_VIEW: 'プライベート ビュー',
  LABEL_CREATE_SERIES: 'シリーズを作成',
  LABEL_SERIES_LIST: 'シリーズ一覧',
  //COMMENTS
  LABEL_COMMENT_HIDE: 'コメントを非表示',
  LABEL_COMMENT_SHOW: 'コメントを表示',
  LABEL_COMMENT: 'コメント',
  LABEL_COMMENTS: 'コメント',
  LABEL_VIEW: '意見',
  LABEL_REPLIES: '返信',
  LABEL_REPLY: '返事',
  LABEL_HIDE_REPLY: '返信を非表示',
  LABEL_HIDE_REPLIES: '返信を非表示',
  LABEL_CANCEL: 'キャンセル',
  LABEL_ADD_A_REPLY: 'スレッドに返信',
  LABEL_ADD_A_COMMENT: 'コメントを追加...',
  LABEL_PLEASE_SIGNIN_COMMENT: 'コメントを追加するにはサインインしてください。',
  LABEL_MORE_COMMENTS: 'その他のコメント',
  LABEL_SHOW_MORE_REPLIES: 'もっと返信を表示',
  LABEL_ADD_EDIT_COMMENT: 'コメントを編集します。',
  LABEL_BEST: '一番',
  LABEL_NEWEST: '最新',
  LABEL_OLDEST: '最も古い',
  LABEL_EDIT: '編集',
  LABEL_ERROR_COMMENT_NOT_EXIST: 'コメントがありません。',
  LABEL_ERROR_VOTE_OWN_COMMENT: '自分のコメントに投票することはできません。',
  LABEL_ERROR_ALREADY_UPVOTE:
    'あなたはすでにこのコメントに賛成票を投じています。',
  LABEL_ERROR_ALREADY_DOWNVOTE:
    'あなたはすでにこのコメントに反対票を投じています。',
  LABEL_CONFIRM_DELETE_COMMENT: 'このコメントを削除しますか?',
  //BACKEND ERROR MESSAGE
  ERR_MSG_USERNAME_EXIST: 'ユーザー名が既に使われています',
  ERR_MSG_WRONG_USERNAME_OR_PASSWORD:
    'ユーザーネームまたはパスワードが違います',
  ERR_MSG_REQUEST_LIMIT: 'リクエスト制限リーチ！後でもう一度やり直してください',
  ERR_MSG_DEFAULT: 'エラーが発生しました。後でもう一度やり直してください',
  ERR_MSG_EMAIL_EXIST: '同じメールアドレスのユーザーが存在します',
  SOCIAL_EMAIL_ERROR_MESSAGE:
    '使用しようとしたメールアドレスのアカウントが既に存在するようです。',
  TOOLTIP_WEBSITE_LANGUAGE: 'ウェブサイト全体の言語を変更します',
  TOOLTIP_COMICS_LANGUAGES: '読みたい漫画の言語フィルター',
  LABEL_MY_DASHBOARD: 'マイ ダッシュボード',
};

export default common;
