const genres = {
  GENRE_ALL: '全部',
  GENRE_ACTION: '行动',
  GENRE_ADVENTURE: '冒险',
  GENRE_COMEDY: '喜剧',
  GENRE_CYBERPUNK: '赛博朋克',
  GENRE_DEMONS: '恶魔',
  GENRE_DRAMA: '戏剧',
  GENRE_FANTASY: '幻想',
  GENRE_GAME: '游戏',
  GENRE_HISTORICAL: '历史',
  GENRE_HORROR: '恐怖',
  GENRE_KIDS: '孩子们',
  GENRE_LGBTQ: 'LGBTQ+',
  GENRE_MAGIC: '魔法',
  GENRE_MATURE: '成熟',
  GENRE_MECHA: '机甲',
  GENRE_MILITARY: '军队',
  GENRE_MUSIC: '音乐',
  GENRE_MYSTERY: '神秘',
  GENRE_PARODY: '戏仿',
  GENRE_POLICE: '警察',
  GENRE_POST_APOCALYPTIC: '后世界末日',
  GENRE_PSYCHOLOGICAL: '心理',
  GENRE_REVERSE_HAREM: '反向后宫',
  GENRE_ROMANCE: '浪漫',
  GENRE_SCHOOL: '学校',
  GENRE_SCI_FI: '科幻',
  GENRE_SLICE_OF_LIFE: '生活的片段',
  GENRE_SPACE: '空间',
  GENRE_SPORTS: '运动的',
  GENRE_SUPER_POWER: '超能力',
  GENRE_SUPERNATURAL: '超自然',
  GENRE_TRAGEDY: '悲剧',
  GENRE_VAMPIRE: '吸血鬼'
};
export default genres;