const common = {
  LABEL_FILTERS: 'Filtres',
  LABEL_CHAPTERS: 'Chapitres',
  LABEL_CHAPTER: 'Chapitre',
  LABEL_SERIES: 'Série',
  LABEL_CREATOR: 'Créateur',
  LABEL_SEARCH: 'Chercher',
  LABEL_ACCOUNT: 'Mon compte',
  LABEL_SIGN_IN: "S'identifier",
  AUTH_MODAL_HEADING:
    'Be part of a community of passionate comic readers, writers, and artists.',
  LABEL_CREATE: 'Create',
  LABEL_INSTEAD: ' instead',
  LABEL_EMAIL: 'E-mail',
  LABEL_USERNAME: "Nom d'utilisateur",
  LABEL_PASSWORD: 'Mot de passe',
  LABEL_NEXT: 'Prochain',
  LABEL_PROCEED: 'Procéder',
  LABEL_ONGOING: 'En cours',
  LABEL_COLLABORATORS: 'Collaborateurs',
  LABEL_NO_COLLABORATORS: 'Aucun collaborateur',
  LABEL_ADD: 'Ajouter',
  LABEL_REMOVE: 'Retirer',
  LABEL_CAN_EDIT: 'Peut éditer',
  LABEL_CAN_VIEW: 'Peut voir',
  LABEL_SHARE_WITH_SOMEONE_PLACEHOLDER: "Partager avec quelqu'un...",
  LABEL_LOADING: 'Chargement...',
  LABEL_PAGE: 'Page',
  LABEL_PAGES: 'Pages',
  LABEL_AUTH_GUARD_CHECKING_AUTH: 'Checking authentication',
  LABEL_AUTH_GUARD_REDIRECT_MSG:
    "Non authentifié - nous vous redirigerons vers l'accueil",
  LABEL_USER_CARD_TITLE: 'Anonyme',
  LABEL_USER_CARD_SUB_HEADER:
    'Connectez-vous ou rejoignez-nous en créant un compte',
  LABEL_READS: 'Lit',
  LABEL_LIKES: 'Aime',
  LABEL_LIKE: 'Comme',
  LABEL_PRIVACY_POLICY: 'Politique de confidentialité',
  LABEL_TERMS_OF_SERVICE: "Conditions d'utilisation",
  LABEL_COOKIE_POLICY: 'Politique relative aux cookies',
  LABEL_SIGN_UP: "S'inscrire",
  LABEL_SETTINGS: 'Réglages',
  LABEL_LANGUAGES: 'Langues',
  LABEL_FAQ: 'Aide et FAQ',
  LABEL_APPS: 'applications',
  FOOTER_ABOUT_US:
    'Be part of a community of passionate comic readers, writers, and artists',
  LABEL_SEARCH_SERIES: 'Searching for series...',
  LABEL_MY_PROFILE: 'My Profile',
  LABEL_MY_ACCOUNT_SETTINGS: 'My Account Settings',
  LABEL_SIGNED_IN_AS: 'Signed in as',
  LABEL_NO_SERIES_FOUND: 'No Series Found',
  LABEL_PRIVATE_VIEW: 'Private View',
  LABEL_CREATE_SERIES: 'Create Series',
  LABEL_SERIES_LIST: 'Series List',
  //COMMENTS
  LABEL_COMMENT_HIDE: 'Masquer les commentaires',
  LABEL_COMMENT_SHOW: 'Afficher les commentaires',
  LABEL_COMMENT: 'Commentaire',
  LABEL_COMMENTS: 'commentaires',
  LABEL_VIEW: 'Voir',
  LABEL_REPLIES: 'réponses',
  LABEL_REPLY: 'Réponse',
  LABEL_HIDE_REPLY: 'Masquer la réponse',
  LABEL_HIDE_REPLIES: 'Masquer les réponses',
  LABEL_CANCEL: 'Annuler',
  LABEL_ADD_A_REPLY: 'Répondre au fil',
  LABEL_ADD_A_COMMENT: 'Ajouter un commentaire...',
  LABEL_PLEASE_SIGNIN_COMMENT:
    'Veuillez vous inscrire pour ajouter un commentaire.',
  LABEL_MORE_COMMENTS: 'Plus de commentaires',
  LABEL_SHOW_MORE_REPLIES: 'Afficher plus de réponses',
  LABEL_ADD_EDIT_COMMENT: 'Modifier le commentaire.',
  LABEL_BEST: 'Meilleur',
  LABEL_NEWEST: 'Le plus récent',
  LABEL_OLDEST: 'Le plus ancien',
  LABEL_EDIT: 'Éditer',
  LABEL_ERROR_COMMENT_NOT_EXIST: "Le commentaire n'existe pas.",
  LABEL_ERROR_VOTE_OWN_COMMENT:
    'Vous ne pouvez pas voter votre propre commentaire.',
  LABEL_ERROR_ALREADY_UPVOTE: 'Vous avez déjà voté pour ce commentaire.',
  LABEL_ERROR_ALREADY_DOWNVOTE: 'Vous avez déjà voté contre ce commentaire.',
  LABEL_CONFIRM_DELETE_COMMENT: 'Voulez-vous supprimer ce commentaire?',
  //BACKEND ERROR MESSAGE
  ERR_MSG_USERNAME_EXIST: "Nom d'utilisateur est déjà utilisé",
  ERR_MSG_WRONG_USERNAME_OR_PASSWORD: 'identifiant ou mot de passe incorrect',
  ERR_MSG_REQUEST_LIMIT:
    "Demander l'atteinte de la limite ! Veuillez réessayer plus tard",
  ERR_MSG_DEFAULT:
    "Oups quelque chose s'est mal passé ! Veuillez réessayer plus tard",
  ERR_MSG_EMAIL_EXIST: 'Un utilisateur avec la même adresse e-mail existe',
  SOCIAL_EMAIL_ERROR_MESSAGE:
    "Il semble qu'un compte avec l'e-mail que vous avez essayé d'utiliser existe déjà.",
  TOOLTIP_WEBSITE_LANGUAGE: 'Change la langue de tout le site Web',
  TOOLTIP_COMICS_LANGUAGES:
    'Filtre de langue pour les bandes dessinées que vous souhaitez lire',
  LABEL_MY_DASHBOARD: 'Mon tableau de bord',
};

export default common;
