const authModal = {
  LABEL_FORGOT_PASSWORD: 'Forgot password?',
  LABEL_FORGOT_USERNAME: 'Forgot username?',
  LABEL_USERNAME_OR_EMAIL: 'Username or Email',
  LABEL_CONTINUING_TERMS: 'By continuing, you agree to our',
  LABEL_TERMS_OF_USE: 'Terms of Use',
  LABEL_CREATE_AN_ACCOUNT: 'Create an account',
  LABEL_OR_SIGN_IN_WITH: 'or sign in with',
  LABEL_INCORRECT_EMAIL: 'Incorrect email address',
  LABEL_OR_SIGN_UP_WITH: 'or sign up with',
  LABEL_PASSWORD: 'Password',
  LABEL_ONE_MORE_STEP_AHEAD: 'One more step ahead!',
  LABEL_WE_SENT: 'We’ve sent a',
  LABEL_6_CHAR_CODE: '6 character code',
  LABEL_TO_THIS_EMAIL: 'to this email',
  LABEL_TO_VERIFY_YOUR_ACCOUNT: 'to verify your account',
  LABEL_TO_VERIFY_ITS_YOU: "to verify that it's you",
  LABEL_VERIFY: 'Verify',
  LABEL_RESEND_CODE: 'Re-send code',
  LABEL_TY_JOINING_US: 'Thank you for joining us!',
  LABEL_SIGNUP_SUCCESS_MSG: 'Your account has been successfully verified. You can now sign in using your credentials, or click proceed to setup your initial profile.',
  LABEL_CHECKING_IF_USER_EXISTS: 'Checking if user exists',
  LABEL_SIGNIN_INSTEAD: 'Sign-in instead',
  LABEL_CHANGE_PASSWORD: 'Change password',
  LABEL_PASSWORD_RESET_SUCCESS: 'Password reset success!',
  LABEL_SUCCESS_CHANGE_PASSWORD: 'Your new password has been successfully set. You can now sign in using your new password, or click proceed to be signed in directly.',
  LABEL_VERIFICATION_FORM_INSTRUCTION: 'on the email you used creating this account. Please put the code in the form to verify your account',
  FORM_VALIDATION_EMAIL_REQUIRED: 'Email is required',
  FORM_VALIDATION_USERNAME_MATCH: 'Sorry, only letters (a-z), numbers (0-9), special characters (.-_) no space are allowed.',
  FORM_VALIDATION_USERNAME_MAX: 'Username must have length less than or equal to 32',
  FORM_VALIDATION_USERNAME_REQUIRED: 'Username is required',
  FORM_VALIDATION_PASSWORD_REQUIRED: 'Password is required',
  FORM_VALIDATION_PASSWORD_MIN: 'Must be longer than 12 characters',
  FORM_VALIDATION_CODE_REQUIRED: 'Code is required',
  FORM_VALIDATION_CODE_MIN: 'Must be 6 characters',
  FORM_VALIDATION_CODE_MAX: 'Must be 6 characters',
  FORM_VALIDATION_NEW_PASSWORD_REQUIRED: 'New password is required'
};
export default authModal;